import '@/assets/css/index.css';
import '@/app/models/socket';
import '@/app/view/index_view';
import { onPier } from '@/app/view/pier/pier_view';
onPier();
import { onViewPlayer } from '@/app/view/sound_view';
onViewPlayer();
import '@/app/view/grid/grid_view';
import '@/app/controllers/listener';
import { soundListener } from '@/app/view/sound_view';
soundListener();
